dubbo:
  application:
    name: dubbo-boot-client
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  scan:
    base-package: com.demo.dubbo.dubbobootclient
  protocol:
    name: dubbo
server:
  port: 8002