spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

dubbo:
  application:
    name: dubbo-boot-service
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  scan:
    base-package: com.demo.dubbo.dubbobootservice
  protocol:
    name: dubbo
server:
  port: 8001